# pytorch_lightning==1.8.1
seed_everything: 420
model:
  tail_pass: wave_res
  wavelet_family: db2
  data_shape: [ 3,128,128 ]
ckpt_path: null
data:
  class_path: dataset.div2k.Div2kDataModule
  init_args:
    batch_size: 8
    path: /Volumes/john/datasets/DIV2K/DIV2K_train_HR
    cache_path: /Volumes/john/datasets/DIV2K/DIV2K_cache
    patch_size: 128
    dataset_repeats: 1
    interpolation: bilin
    test_percent: 0.10
    upsample_size: 4
    num_workers: 8