# pytorch_lightning==1.8.1
seed_everything: 420
model:
  tail_pass: std
  wavelet_family: bior2.2
  data_shape: [ 3,128,128 ]
  warmup_batches: 1000
  discriminator_normalization: bn
  generator_normalization:
  aa_discrim: False
trainer:
  accumulate_grad_batches: 1
  accelerator: gpu
  gradient_clip_val: 0.5
  max_epochs: 100
#  callbacks:
#    - class_path: StochasticWeightAveraging
#      init_args:
#        swa_lrs: 1e-2
ckpt_path: null
data:
  class_path: dataset.div2k.Div2kDataModule
  init_args:
    batch_size: 4
    path: /mnt/home/john/datasets/DIV2K/DIV2K_train_HR
    cache_path: /mnt/ramdisk
    patch_size: 128
    dataset_repeats: 20
    interpolation: bilin
    test_percent: 0.10
    upsample_size: 4
    num_workers: 16